name: daily one report

on:
  workflow_dispatch: # 手动触发

  schedule: # 定时触发
    # cron表达式，时区是UTC时间，比我们早8小时，如下所表示的是16表示的是每天0点0分
    - cron: '0 16 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    environment: ProductionOne

    steps:
      # 输出IP
      - name: IP
        run: sudo curl ifconfig.me

      # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # 检出
      - name: Checkout
        uses: actions/checkout@v2
        
      # 环境
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      # 安装依赖项
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      # 执行
      - name: 'execute report'
        run: |
          python request2json.py
          python oneReport.py ${{ secrets.STUDENTID }} ${{ secrets.PASSWORD }} ${{ secrets.LOCATION }} ${{ secrets.MAIL_USERNAME }} ${{ secrets.MAIL_PASSWORD }} ${{ secrets.MAIL_BOX }}
        
