# This is a basic workflow to help you get started with Actions

name: daily report

# Controls when the action will run. 
on:
  workflow_dispatch: # 手动触发
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule: # 定时触发
    # cron表达式，时区是UTC时间，比我们早8小时，如下所表示的是16表示的是每天0点0分
    - cron: '0,0 16,10 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
      # 输出IP
      - name: IP
        run: sudo curl ifconfig.me

      # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # 检出
      - name: Checkout
        uses: actions/checkout@v2
        
      # 环境
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # 安装依赖项
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      # 执行
      - name: 'execute report'
        run: python report.py ${{ secrets.STUDENTID }} ${{ secrets.PASSWORD }}
        
      # 获取格式化的日期并存入GitHub内置的环境变量中
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      
      # 发送邮件
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          # 这些是发送邮件需要配置的参数，更多详细的说明请访问具体的仓库
          server_address: smtp.163.com
          server_port: 465
          # 这些secret的环境变量需要配置在setting中的secret下
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 每日一报 (${{env.REPORT_DATE}})
          body: file://mail.html
          to: ${{ secrets.MAIL_BOX }}
          from: GitHub Actions
          content_type: text/html
